language: go

go_import_path: github.com/aws/aws-xray-sdk-go

sudo: required

go:
  - "1.9"
  - "1.10"
  - "1.11" 
  - "1.12"
  - "tip"

notifications:
  email:
    recipients:
      - aws-xray-peryton@amazon.com
    on_success: never
    on_failure: always

env:
  - DEP_VERSION="0.5.1" GO111MODULE="on"

before_install:
  - echo $TRAVIS_GO_VERSION
  - if [ $TRAVIS_GO_VERSION == "1.9" ] ||
    [ $TRAVIS_GO_VERSION == "1.10" ]; then
      export DEP_MANAGEMENT_TOOL="DEP";
    else
      export DEP_MANAGEMENT_TOOL="MODULE";
    fi
  - echo $DEP_MANAGEMENT_TOOL
  - if [ $DEP_MANAGEMENT_TOOL == "DEP" ]; then
      curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep;
      chmod +x $GOPATH/bin/dep;
    fi

install:
  - if [ $DEP_MANAGEMENT_TOOL == "DEP" ]; then
      dep ensure;
    else
      go get;
    fi

script:
  - make test

matrix:
  allow_failures:
    - go: tip