language: go

go_import_path: github.com/aws/aws-xray-sdk-go

sudo: required

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "tip"

notifications:
  email:
    recipients:
      - aws-xray-peryton@amazon.com
    on_success: never
    on_failure: always

env:
  - DEP_VERSION="0.5.1" GO111MODULE="on"

before_install:
  - echo $TRAVIS_GO_VERSION
  - if [ $TRAVIS_GO_VERSION == "1.9" ] ||
    [ $TRAVIS_GO_VERSION == "1.10" ]; then
      export DEP_MANAGEMENT_TOOL="DEP";
    else
      export DEP_MANAGEMENT_TOOL="MODULE";
    fi
  - echo $DEP_MANAGEMENT_TOOL
  - if [ $DEP_MANAGEMENT_TOOL == "DEP" ]; then
      curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep;
      chmod +x $GOPATH/bin/dep;
    fi

install:
  - if [ $DEP_MANAGEMENT_TOOL == "DEP" ]; then
      dep ensure;
    else
      go get;
    fi
  # Only bother running lints on the latest version.  Some of the linters fail to install on older versions of go.
  - if [ $TRAVIS_GO_VERSION == "1.12" ]; then
      go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.16.0;
    fi

script:
  - make test-with-race
  # We are in the process of resolving all the lint warnings for x-ray-sdk-go.  Still run the linter to expose these
  # and resolve to clean these up.
  - if [ $TRAVIS_GO_VERSION == "1.12" ]; then
      make golangci-lint || true;
    fi

matrix:
  allow_failures:
    - go: tip