name: Continuous monitoring of distribution channels
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

permissions:
  id-token: write
  contents: read

jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2.7.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a #v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_INTEG_TEST_ROLE_ARN }}
          aws-region: us-east-1
      
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 #v2.2.0
        with:
          go-version: '^1.16'
      
      - name: Run distribution test
        id: distribution-availability
        run: |
          go mod tidy
          go test distributioncheck
        working-directory: integration-tests/distributioncheck
      
      - name: Publish metric on X-Ray Go SDK distribution availability
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.distribution-availability.outcome }}" == "failure" ]]; then
            aws cloudwatch put-metric-data --metric-name XRayGoSDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 1 --timestamp $(date +%s)
          else
            aws cloudwatch put-metric-data --metric-name XRayGoSDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 0 --timestamp $(date +%s)
          fi

