on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build_push_sample_app_image:
    name: Build and Push Sample App docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2.7.0

      - name: Create a directory
        run: mkdir sample-apps/http-server/aws-xray-sdk-go

      - name: Copy X-Ray SDK to deployment package with Sample App
        run: rsync -r * sample-apps/http-server/aws-xray-sdk-go --exclude sample-apps/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 #v1.7.0

      - name: Cache Docker layer
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a #v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_INTEG_TEST_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Public ECR
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 #v1.14.1
        with:
          registry: public.ecr.aws

      - name: Build image and push to ECR
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a #v2.10.0
        with:
          file: sample-apps/http-server/Dockerfile
          context: .
          tags: public.ecr.aws/s6b4x8l3/aws-xray-go-sdk-sample-app:${{ github.sha }}
          push: true
